### ISSUE TITLE
NbtTag serial name Typo? Maybe?

### ISSUE THREAD

**Issue by milosworks** [BenWoodworth/knbt#46]
https://github.com/BenWoodworth/knbt/blob/6580e06fd3cda898989f1a5cecf4694579c134df/src/commonMain/kotlin/NbtTagSerializers.kt#L16

Shouldnt this be NbtTag instead of using kotlinx jsonelement?

**Comment by BenWoodworth** [comment]
Good catch! Yeah, it should be `"net.benwoodworth.knbt.NbtTag"` similar to the other serializer.

I do have it fixed in pull request #44, but that's on pause because of a new job search and holiday busyness.

I'm open to PRs if you want to contribute that fix, then it's pretty quick to push out a release. Otherwise I can later today or tomorrow when I get a chance!

**Comment by BenWoodworth** [comment]
I just pushed out v0.11.6 with this fixed, so it should be available soon! Thanks for the report :)

**Comment by milosworks** [comment]
> I just pushed out v0.11.6 with this fixed, so it should be available soon! Thanks for the report :)

Thanks so much, sorry I couldn't PR I got busy, it wasn't critical on my end but I'm happy it's now fixed :D

**Comment by milosworks** [comment]
Btw I wanted to ask in here https://github.com/BenWoodworth/knbt/commit/df89582decadb699ca70b849afec8aa9a870c29a my issue is already fixed bc it's not JsonElement and the name doesn't really matter but shouldn't it be NbtTag instead of NbtByte? or maybe I'm missing something? the name doesn't really matter anyways

**Comment by BenWoodworth** [comment]
You... are a life saver 😅

It should be NbtTag. I didn't even copy-paste this time, I just typed out the same name as the next serializer on autopilot in my haste. I'll get right on that!

**Comment by BenWoodworth** [comment]
And, done! The name might actually matter in some cases, since the serial name may be used as a key to look up serializers contextually, so should be unique. Now though, with 0.11.7 pushed out, it *should* be good to go :melting_face:
