### ISSUE TITLE
[FEATURE] A JsonPath-like DSL for reading specific properties from an NBT source

### ISSUE THREAD

**Issue by RaphaelTarita** [BenWoodworth/knbt#6]
It'd be cool to have a DSL that allows you to access specifc properties of an arbitrary NBT source without needing a model class. Similar to how [KotlinNBT](https://github.com/luizrcs/KotlinNBT) does it or how I plan to do it in [my version](https://github.com/RaphaelTarita/KXSmine).

The DSL definitions for KotlinNBT can be found [here](https://github.com/luizrcs/KotlinNBT/blob/master/src/main/kotlin/Tag.kt). An example of this DSL would be:

```kotlin
val fibonacci: IntArray = nbt["testCompound"].asTagCompound["fibonacciWithoutZero"].asIntArray
val message: String = nbt["testList"].asTagList[0].asTagCompound["firstString"].asString
val timestamp: Long = nbt["timestamp"].asLong
```

The DSL definitions for KXSmine can be found [here](https://github.com/RaphaelTarita/KXSmine/blob/develop/src/commonMain/kotlin/msw/extras/kxsmine/dsl/access/accessdsl.kt). An example of this DSL would be:

```kotlin
val fibonacci = root.compound("testCompound").intarray("fibonacciWithoutZero").data
val message = root.list("testList").compoundAt(0).string("firstString").data
val timestamp = root.long("timestamp").data
```

The main benefit from such a DSL would be the ability to type-safely access just specific properties without having to write a whole model class for the NBT source you're parsing.

**Comment by BenWoodworth** [comment]
Good idea! I'm closely following kotlinx.serialization's conventions, so copying [the approach used with JSON](https://github.com/Kotlin/kotlinx.serialization/blob/3aa8122310fa9d0f95095453875ae24c8cbb1b1c/formats/json/commonMain/src/kotlinx/serialization/json/JsonElement.kt#L148-L234) should work.

So based on that, what do you think about adding a bunch of `.nbt*` properties that cast to the specific tag type?

And for primitives do you think there should also/instead be `.byte`, `.int`, `.string`, etc. properties to return the value directly? I'm not sure there's a good use case for `tag.nbtByte` if we already have `tag.byte`.

**Comment by BenWoodworth** [comment]
If you want to make a PR (to the `0.6` branch), adding these properties to [NbtTag.kt](https://github.com/BenWoodworth/knbt/blob/d2742cdf36bbf7c0a597469822b370bc63bc2333/src/commonMain/kotlin/tag/NbtTag.kt) would be a good start. Otherwise I'll get to this when I have the time

Primitives (returns `Byte`, etc.): `byte`, `short`, `int`, `long`, `float`, `double`, `string`
Tags (returns `Nbt*`): `nbtByteArray`, `nbtIntArray`, `nbtLongArray`, `nbtList`, `nbtCompound`

**Comment by RaphaelTarita** [comment]
Sounds good! I'll get to that when I have time, so I guess whoever's faster gets to do it 😅
